"""Short spoken / SMS phrases in every scheduled Indian language (+ English), used when Gemini is
not writing the text itself: the read-back after a report, the follow-up question, and the IVR
"please check" prompt for implausible numbers.

Quality note: en, hi, ta, kn, or, bn, te, mr, gu, ml, pa, ur were written with care; as, mai, ne,
kok, doi, sa, ks, sd, sat, mni and brx are drafts that need a native-speaker review before a field
pilot (see README). Any missing key falls back to English."""

# key -> {confirm, beds_occupied, staff_present, opd_count, follow_up, received, discarded,
#         ivr_check, usual, unclear}
P = {
    "en": dict(confirm="Thank you. Recorded for {phc}: {items}.", beds_occupied="beds occupied",
               staff_present="staff present", opd_count="OPD patients",
               follow_up="How many beds are occupied and how many staff are present today?",
               received="received", discarded="discarded",
               ivr_check="Please check: {items}. If these numbers are correct, say yes. Otherwise, say the correct numbers.",
               usual="usually about {n}", unclear="the recording was not clear"),
    "hi": dict(confirm="धन्यवाद। {phc} के लिए दर्ज किया गया: {items}।", beds_occupied="भरे बिस्तर",
               staff_present="उपस्थित स्टाफ", opd_count="ओपीडी मरीज़",
               follow_up="आज कितने बिस्तर भरे हैं और कितने स्टाफ उपस्थित हैं?", received="प्राप्त", discarded="नष्ट",
               ivr_check="कृपया जाँच लें: {items}। अगर ये संख्याएँ सही हैं, तो हाँ कहें। नहीं तो सही संख्याएँ बताएँ।",
               usual="आम तौर पर लगभग {n}", unclear="रिकॉर्डिंग साफ़ नहीं थी"),
    "bn": dict(confirm="ধন্যবাদ। {phc}-এর জন্য নথিভুক্ত হয়েছে: {items}।", beds_occupied="ভর্তি শয্যা",
               staff_present="উপস্থিত কর্মী", opd_count="OPD রোগী",
               follow_up="আজ কতগুলি শয্যা ভর্তি এবং কতজন কর্মী উপস্থিত?", received="প্রাপ্ত", discarded="নষ্ট",
               ivr_check="অনুগ্রহ করে যাচাই করুন: {items}। সংখ্যাগুলি সঠিক হলে 'হ্যাঁ' বলুন। না হলে সঠিক সংখ্যাগুলি বলুন।",
               usual="সাধারণত প্রায় {n}", unclear="রেকর্ডিং পরিষ্কার ছিল না"),
    "te": dict(confirm="ధన్యవాదాలు. {phc} కోసం నమోదు చేయబడింది: {items}.", beds_occupied="నిండిన పడకలు",
               staff_present="హాజరైన సిబ్బంది", opd_count="OPD రోగులు",
               follow_up="ఈరోజు ఎన్ని పడకలు నిండి ఉన్నాయి, ఎంతమంది సిబ్బంది హాజరయ్యారు?", received="అందుకున్నది",
               discarded="పాడైనది",
               ivr_check="దయచేసి సరిచూడండి: {items}. ఈ సంఖ్యలు సరైనవైతే 'అవును' అనండి. లేకపోతే సరైన సంఖ్యలు చెప్పండి.",
               usual="సాధారణంగా దాదాపు {n}", unclear="రికార్డింగ్ స్పష్టంగా లేదు"),
    "mr": dict(confirm="धन्यवाद. {phc} साठी नोंद केली: {items}.", beds_occupied="भरलेले बेड",
               staff_present="उपस्थित कर्मचारी", opd_count="OPD रुग्ण",
               follow_up="आज किती बेड भरलेले आहेत आणि किती कर्मचारी उपस्थित आहेत?", received="मिळाले", discarded="नष्ट",
               ivr_check="कृपया तपासा: {items}. हे आकडे बरोबर असल्यास 'हो' म्हणा. नाहीतर बरोबर आकडे सांगा.",
               usual="साधारणपणे सुमारे {n}", unclear="रेकॉर्डिंग स्पष्ट नव्हते"),
    "ta": dict(confirm="நன்றி. {phc} க்காக பதிவு செய்யப்பட்டது: {items}.", beds_occupied="நிரம்பிய படுக்கைகள்",
               staff_present="பணியிலுள்ள ஊழியர்கள்", opd_count="புறநோயாளிகள்",
               follow_up="இன்று எத்தனை படுக்கைகள் நிரம்பியுள்ளன, எத்தனை ஊழியர்கள் வந்துள்ளனர்?", received="பெறப்பட்டது",
               discarded="அழிக்கப்பட்டது",
               ivr_check="தயவுசெய்து சரிபாருங்கள்: {items}. இந்த எண்கள் சரியென்றால் 'ஆம்' என்று சொல்லுங்கள். இல்லையெனில் சரியான எண்களைச் சொல்லுங்கள்.",
               usual="வழக்கமாக சுமார் {n}", unclear="பதிவு தெளிவாக இல்லை"),
    "ur": dict(confirm="شکریہ۔ {phc} کے لیے درج کیا گیا: {items}۔", beds_occupied="بھرے ہوئے بستر",
               staff_present="حاضر عملہ", opd_count="OPD مریض",
               follow_up="آج کتنے بستر بھرے ہیں اور کتنا عملہ حاضر ہے؟", received="موصول", discarded="ضائع",
               ivr_check="براہ کرم جانچ لیں: {items}۔ اگر یہ نمبر درست ہیں تو 'ہاں' کہیں۔ ورنہ درست نمبر بتائیں۔",
               usual="عام طور پر تقریباً {n}", unclear="ریکارڈنگ صاف نہیں تھی"),
    "gu": dict(confirm="આભાર. {phc} માટે નોંધાયું: {items}.", beds_occupied="ભરેલા પલંગ",
               staff_present="હાજર સ્ટાફ", opd_count="OPD દર્દીઓ",
               follow_up="આજે કેટલા પલંગ ભરેલા છે અને કેટલો સ્ટાફ હાજર છે?", received="મળેલ", discarded="નષ્ટ",
               ivr_check="કૃપા કરીને ચકાસો: {items}. જો આ આંકડા સાચા હોય તો 'હા' કહો. નહીં તો સાચા આંકડા કહો.",
               usual="સામાન્ય રીતે આશરે {n}", unclear="રેકોર્ડિંગ સ્પષ્ટ ન હતું"),
    "kn": dict(confirm="ಧನ್ಯವಾದಗಳು. {phc} ಗಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ: {items}.", beds_occupied="ಭರ್ತಿಯಾದ ಹಾಸಿಗೆಗಳು",
               staff_present="ಹಾಜರಿರುವ ಸಿಬ್ಬಂದಿ", opd_count="ಹೊರರೋಗಿಗಳು",
               follow_up="ಇಂದು ಎಷ್ಟು ಹಾಸಿಗೆಗಳು ಭರ್ತಿಯಾಗಿವೆ ಮತ್ತು ಎಷ್ಟು ಸಿಬ್ಬಂದಿ ಹಾಜರಿದ್ದಾರೆ?", received="ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
               discarded="ನಾಶಪಡಿಸಲಾಗಿದೆ",
               ivr_check="ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ: {items}. ಈ ಸಂಖ್ಯೆಗಳು ಸರಿಯಾಗಿದ್ದರೆ 'ಹೌದು' ಎನ್ನಿ. ಇಲ್ಲದಿದ್ದರೆ ಸರಿಯಾದ ಸಂಖ್ಯೆಗಳನ್ನು ಹೇಳಿ.",
               usual="ಸಾಮಾನ್ಯವಾಗಿ ಸುಮಾರು {n}", unclear="ರೆಕಾರ್ಡಿಂಗ್ ಸ್ಪಷ್ಟವಾಗಿರಲಿಲ್ಲ"),
    "or": dict(confirm="ଧନ୍ୟବାଦ। {phc} ପାଇଁ ରେକର୍ଡ କରାଗଲା: {items}।", beds_occupied="ଭର୍ତ୍ତି ଶଯ୍ୟା",
               staff_present="ଉପସ୍ଥିତ କର୍ମଚାରୀ", opd_count="ଓପିଡି ରୋଗୀ",
               follow_up="ଆଜି କେତୋଟି ଶଯ୍ୟା ଭର୍ତ୍ତି ଅଛି ଏବଂ କେତେ ଜଣ କର୍ମଚାରୀ ଉପସ୍ଥିତ ଅଛନ୍ତି?", received="ପ୍ରାପ୍ତ",
               discarded="ନଷ୍ଟ",
               ivr_check="ଦୟାକରି ଯାଞ୍ଚ କରନ୍ତୁ: {items}। ଏହି ସଂଖ୍ୟା ଠିକ୍ ଥିଲେ 'ହଁ' କୁହନ୍ତୁ। ନହେଲେ ଠିକ୍ ସଂଖ୍ୟା କୁହନ୍ତୁ।",
               usual="ସାଧାରଣତଃ ପ୍ରାୟ {n}", unclear="ରେକର୍ଡିଂ ସ୍ପଷ୍ଟ ନଥିଲା"),
    "ml": dict(confirm="നന്ദി. {phc}-ക്കായി രേഖപ്പെടുത്തി: {items}.", beds_occupied="നിറഞ്ഞ കിടക്കകൾ",
               staff_present="ഹാജരായ ജീവനക്കാർ", opd_count="OPD രോഗികൾ",
               follow_up="ഇന്ന് എത്ര കിടക്കകൾ നിറഞ്ഞിട്ടുണ്ട്, എത്ര ജീവനക്കാർ ഹാജരുണ്ട്?", received="ലഭിച്ചത്",
               discarded="നശിപ്പിച്ചത്",
               ivr_check="ദയവായി പരിശോധിക്കുക: {items}. ഈ സംഖ്യകൾ ശരിയാണെങ്കിൽ 'അതെ' എന്ന് പറയുക. അല്ലെങ്കിൽ ശരിയായ സംഖ്യകൾ പറയുക.",
               usual="സാധാരണ ഏകദേശം {n}", unclear="റെക്കോർഡിംഗ് വ്യക്തമായിരുന്നില്ല"),
    "pa": dict(confirm="ਧੰਨਵਾਦ। {phc} ਲਈ ਦਰਜ ਕੀਤਾ ਗਿਆ: {items}।", beds_occupied="ਭਰੇ ਬਿਸਤਰੇ",
               staff_present="ਹਾਜ਼ਰ ਸਟਾਫ਼", opd_count="OPD ਮਰੀਜ਼",
               follow_up="ਅੱਜ ਕਿੰਨੇ ਬਿਸਤਰੇ ਭਰੇ ਹਨ ਅਤੇ ਕਿੰਨਾ ਸਟਾਫ਼ ਹਾਜ਼ਰ ਹੈ?", received="ਪ੍ਰਾਪਤ", discarded="ਨਸ਼ਟ",
               ivr_check="ਕਿਰਪਾ ਕਰਕੇ ਜਾਂਚ ਕਰੋ: {items}। ਜੇ ਇਹ ਅੰਕੜੇ ਸਹੀ ਹਨ ਤਾਂ 'ਹਾਂ' ਕਹੋ। ਨਹੀਂ ਤਾਂ ਸਹੀ ਅੰਕੜੇ ਦੱਸੋ।",
               usual="ਆਮ ਤੌਰ 'ਤੇ ਲਗਭਗ {n}", unclear="ਰਿਕਾਰਡਿੰਗ ਸਾਫ਼ ਨਹੀਂ ਸੀ"),
    "as": dict(confirm="ধন্যবাদ। {phc}ৰ বাবে লিপিবদ্ধ কৰা হ'ল: {items}।", beds_occupied="ভৰ্তি বিছনা",
               staff_present="উপস্থিত কৰ্মচাৰী", opd_count="OPD ৰোগী",
               follow_up="আজি কিমান বিছনা ভৰ্তি আৰু কিমানজন কৰ্মচাৰী উপস্থিত আছে?", received="প্ৰাপ্ত", discarded="নষ্ট",
               ivr_check="অনুগ্ৰহ কৰি পৰীক্ষা কৰক: {items}। এই সংখ্যাবোৰ শুদ্ধ হ'লে 'হয়' বুলি কওক। নহ'লে শুদ্ধ সংখ্যাবোৰ কওক।",
               usual="সাধাৰণতে প্ৰায় {n}", unclear="ৰেকৰ্ডিং স্পষ্ট নাছিল"),
    "mai": dict(confirm="धन्यवाद। {phc} लेल दर्ज कएल गेल: {items}।", beds_occupied="भरल बिछाओन",
                staff_present="उपस्थित कर्मचारी", opd_count="OPD रोगी",
                follow_up="आइ कतेक बिछाओन भरल अछि आ कतेक कर्मचारी उपस्थित छथि?", received="प्राप्त", discarded="नष्ट",
                ivr_check="कृपया जाँचि लिअ: {items}। जँ ई संख्या सही अछि तँ 'हँ' कहू। नहि तँ सही संख्या कहू।",
                usual="सामान्यतः लगभग {n}", unclear="रिकॉर्डिंग साफ नहि छल"),
    "sat": dict(confirm="ᱥᱟᱨᱦᱟᱣ᱾ {phc} ᱞᱟᱹᱜᱤᱫ ᱚᱞ ᱫᱚᱦᱚ ᱮᱱᱟ: {items}᱾", beds_occupied="ᱯᱮᱨᱮᱡ ᱠᱷᱟᱴᱤᱭᱟᱹ",
                staff_present="ᱦᱟᱡᱤᱨ ᱠᱟᱹᱢᱤᱭᱟᱹ", opd_count="OPD ᱨᱩᱣᱟᱹ ᱦᱚᱲ",
                follow_up="ᱛᱮᱦᱮᱧ ᱛᱤᱱᱟᱹᱜ ᱠᱷᱟᱴᱤᱭᱟᱹ ᱯᱮᱨᱮᱡ ᱢᱮᱱᱟᱜ-ᱟ ᱟᱨ ᱛᱤᱱᱟᱹᱜ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱦᱟᱡᱤᱨ ᱢᱮᱱᱟᱜ-ᱟ?",
                received="ᱧᱟᱢ ᱮᱱᱟ", discarded="ᱵᱟᱹᱲᱤᱡ ᱮᱱᱟ",
                ivr_check="ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱧᱮᱞ ᱢᱮ: {items}᱾ ᱡᱩᱫᱤ ᱱᱚᱶᱟ ᱮᱞ ᱴᱷᱤᱠ ᱠᱟᱱᱟ ᱮᱱᱠᱷᱟᱱ 'ᱦᱮᱸ' ᱢᱮᱱ ᱢᱮ᱾ ᱵᱟᱝᱠᱷᱟᱱ ᱴᱷᱤᱠ ᱮᱞ ᱢᱮᱱ ᱢᱮ᱾",
                usual="ᱥᱟᱫᱷᱟᱨᱚᱬ ᱛᱮ ᱯᱟᱥᱮ {n}", unclear="ᱨᱮᱠᱚᱨᱰᱤᱝ ᱥᱟᱯᱷᱟ ᱵᱟᱹᱱᱩᱜ ᱠᱟᱱ ᱛᱟᱦᱮᱸᱫ"),
    "ks": dict(confirm="شُکریہ۔ {phc} باپتھ درج کوٚر: {items}۔", beds_occupied="بٔرِتھ بِسترٕ",
               staff_present="حٲضِر عملہٕ", opd_count="OPD مریض",
               follow_up="اَز کیٚتۍ بِسترٕ چھِ بٔرِتھ تہٕ کوٚتاہ عملہٕ چھُ حٲضِر؟", received="مِلیومُت", discarded="خراب",
               ivr_check="مہربٲنی کٔرِتھ کٔرِو جانٛچ: {items}۔ اگر یِم نمبر ٹھیک چھِ، ووٚنِو 'آ'۔ نَتہٕ ووٚنِو ٹھیک نمبر۔",
               usual="عام طور تقریباً {n}", unclear="ریکارڈنگ ٲس نہٕ صاف"),
    "ne": dict(confirm="धन्यवाद। {phc} का लागि दर्ता गरियो: {items}।", beds_occupied="भरिएका शय्या",
               staff_present="उपस्थित कर्मचारी", opd_count="OPD बिरामी",
               follow_up="आज कति शय्या भरिएका छन् र कति कर्मचारी उपस्थित छन्?", received="प्राप्त", discarded="नष्ट",
               ivr_check="कृपया जाँच गर्नुहोस्: {items}। यी संख्या ठीक छन् भने 'हो' भन्नुहोस्। नत्र ठीक संख्या भन्नुहोस्।",
               usual="सामान्यतया करिब {n}", unclear="रेकर्डिङ स्पष्ट थिएन"),
    "sd": dict(confirm="مهرباني. {phc} لاءِ درج ڪيو ويو: {items}.", beds_occupied="ڀريل بسترا",
               staff_present="حاضر عملو", opd_count="OPD مريض",
               follow_up="اڄ ڪيترا بسترا ڀريل آهن ۽ ڪيترو عملو حاضر آهي؟", received="مليل", discarded="خراب",
               ivr_check="مهرباني ڪري جانچ ڪريو: {items}. جيڪڏهن اهي انگ صحيح آهن ته 'ها' چئو. ٻي صورت ۾ صحيح انگ ٻڌايو.",
               usual="عام طور تي لڳ ڀڳ {n}", unclear="رڪارڊنگ صاف نه هئي"),
    "kok": dict(confirm="देव बरें करूं. {phc} खातीर नोंद केली: {items}.", beds_occupied="भरिल्ल्यो खाटी",
                staff_present="हाजीर कर्मचारी", opd_count="OPD दुयेंती",
                follow_up="आयज कितल्यो खाटी भरल्यात आनी कितले कर्मचारी हाजीर आसात?", received="मेळ्ळें", discarded="नश्ट",
                ivr_check="उपकार करून तपासात: {items}. हे आंकडे बरोबर आसल्यार 'व्हय' म्हणात. ना जाल्यार बरोबर आंकडे सांगात.",
                usual="सादारणपणान सुमार {n}", unclear="रेकॉर्डिंग स्पश्ट नाशिल्लें"),
    "doi": dict(confirm="धन्नवाद। {phc} आस्तै दर्ज कीता गेआ: {items}।", beds_occupied="भरोए दे बिस्तरे",
                staff_present="हाजर स्टाफ", opd_count="OPD मरीज",
                follow_up="अज्ज किन्ने बिस्तरे भरोए दे न ते किन्ना स्टाफ हाजर ऐ?", received="थ्होआ", discarded="खराब",
                ivr_check="किरपा करियै जांच करो: {items}। जेकर एह् अंकड़े ठीक न तां 'हां' आखो। नेईं तां ठीक अंकड़े दस्सो।",
                usual="आम तौरा पर लगभग {n}", unclear="रिकार्डिंग साफ नेईं ही"),
    "mni": dict(confirm="ꯊꯥꯒꯠꯆꯔꯤ꯫ {phc}ꯒꯤꯗꯃꯛ ꯏꯔꯛꯂꯦ: {items}꯫", beds_occupied="ꯃꯤꯅꯝꯂꯕ ꯐꯝꯕꯥꯛ",
                staff_present="ꯂꯥꯛꯂꯕ ꯊꯕꯛ ꯇꯧꯕꯁꯤꯡ", opd_count="OPD ꯑꯅꯥꯕꯁꯤꯡ",
                follow_up="ꯉꯁꯤ ꯐꯝꯕꯥꯛ ꯀꯌꯥ ꯃꯤꯅꯝꯂꯤ ꯑꯃꯁꯨꯡ ꯊꯕꯛ ꯇꯧꯕ ꯀꯌꯥ ꯂꯥꯛꯂꯤ?", received="ꯐꯪꯂꯦ", discarded="ꯃꯥꯡꯂꯦ",
                ivr_check="ꯆꯥꯟꯕꯤꯗꯨꯅ ꯌꯦꯡꯁꯤꯟꯕꯤꯌꯨ: {items}꯫ ꯃꯁꯤꯡ ꯑꯁꯤ ꯆꯨꯝꯂꯕꯗꯤ 'ꯍꯣꯏ' ꯍꯥꯌꯕꯤꯌꯨ꯫ ꯆꯨꯝꯗ꯭ꯔꯕꯗꯤ ꯆꯨꯝꯕ ꯃꯁꯤꯡ ꯍꯥꯌꯕꯤꯌꯨ꯫",
                usual="ꯃꯇꯝ ꯄꯨꯝꯅꯃꯛꯇ ꯑꯌꯥꯝꯕ {n}", unclear="ꯔꯦꯀꯣꯔꯗꯤꯡ ꯃꯌꯦꯛ ꯁꯦꯡꯗꯦ"),
    "brx": dict(confirm="सिबियो। {phc} नि थाखाय लिरथानाय जादों: {items}।", beds_occupied="आबुं जानाय बिस्तर",
                staff_present="थानाय स्टाफ", opd_count="OPD बेमारिफोर",
                follow_up="दिनै बेसेबां बिस्तर आबुं जादों आरो बेसेबां स्टाफ थादों?", received="मोनदों", discarded="गाज्रि जादों",
                ivr_check="अननानै नायसं: {items}। जुदि बेफोर अनजिमा थार जायो 'नंगौ' बुङो। नङा जायोब्ला थार अनजिमाफोर बुङो।",
                usual="सरासरि जेबो {n}", unclear="रेकर्डिं गोजों नङा"),
    "sa": dict(confirm="धन्यवादः। {phc} कृते अभिलिखितम्: {items}।", beds_occupied="पूरिताः शय्याः",
               staff_present="उपस्थिताः कर्मकराः", opd_count="OPD रोगिणः",
               follow_up="अद्य कति शय्याः पूरिताः, कति कर्मकराः उपस्थिताः?", received="प्राप्तम्", discarded="नष्टम्",
               ivr_check="कृपया परीक्षध्वम्: {items}। यदि एताः सङ्ख्याः सम्यक् सन्ति तर्हि 'आम्' इति वदतु। अन्यथा सम्यक् सङ्ख्याः वदतु।",
               usual="प्रायः {n}", unclear="ध्वनिमुद्रणं स्पष्टं नासीत्"),
}


def phrase(lang: str, key: str, **kw) -> str:
    s = P.get(lang, {}).get(key) or P["en"][key]
    return s.format(**kw) if kw else s
